spring:
  application:
    name: TEST-APP
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver


flyway:
  enabled: true

server:
  port: 8089

file-storage:
    location: upload-dir

account-details:
  service-uri: tls-test.scnetservices.ru
  service-port: 9000